#
# Standard compiler command line switches
#	d       Redefined macros
#	c       No link
#	AM      Medium memory model
#	Gsw     Stack probes & Windows
#	G2      80286 Instruction Set
#	G3      80386 Instruction Set
#	Gh      C5.1 compatible object
#	Ox      Max optimization (Note: C6.00a float op error for "ei")
#	Od      No optimization
#	W2      Intermediate warning level
#	Zd      Symbolic Debug
#	Zi      CodeView Debug
#	NT      Named text (code area) follows
#	Alnw	Check for DS==SS
#	V       Imbed version string
#
# Standard linker command line switches
#   NOD     No default library
#   A:x     Segment alignment (default = 512 bytes)
#   ST:x    Stack size larger than default 0x800 (2048)

# -----------------------------------------------------------------------
# Compile and Link options (distribution & debug)
# -----------------------------------------------------------------------
!IFDEF deb
# ---- DEBUG ----
ap=masm/MX/V/ZI
cp=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) $(M_Type) -W3 -G2  -Zp -Od -Zi 
lp=link/NOD/NOE/NOI/M/CO$(L_Defs)
!ELSE
# ---- Default: DISTRIBUTION ----
ap=masm/MX/V
cp=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) $(M_Type) -W3 -G2s -Zp -Ox
lp=link/NOD/NOE/NOI/M$(L_Defs)
!ENDIF

# -----------------------------------------------------------------------
# Version Control and Copyright Defs
# -----------------------------------------------------------------------
V_Note = "Copyright VISI, 800-234-VISI"

# -----------------------------------------------------------------------
# Library specific build arguments
# -----------------------------------------------------------------------
!IFDEF mwe
# ---- MS Windows Emulator ----
W_Defs = -DW31
M_Type = -AL -FPi -Mq
M_Name = mwe
L_Libs = llibcewq+libw+llibcew
LnkDef = idxtst
rc = rc -D$(C_Defs) $(W_Defs)
!ELSE
# ---- DEFAULT MS Large Emulator ----
W_Defs = -DDOS
M_Type = -AL -FPi
M_Name = mle
L_Libs = llibce
LnkDef = 
L_Defs = /ST:6144
rc = REM -No Rc-
!ENDIF

# -----------------------------------------------------------------------
# Hardware specific build paths
# -----------------------------------------------------------------------
!IFDEF g21
# ---- CCITT G.721 ----
C_Defs = G21
!ELSE
!IFDEF nwv
# ---- NEW VOICE ----
C_Defs = NWV
!ELSE
!IFDEF mpc
# ---- MPC ----
C_Defs = MPC
!ELSE
!IFDEF ptc
# ---- PTC ----
C_Defs = PTC
!ELSE
!IFDEF rtx
# ---- RHETOREX ----
C_Defs = RTX
!ELSE
!IFDEF tti
# ---- TTI ----
C_Defs = TTI
!ELSE
# ---- DEFAULT ALL ----
C_Defs = ALL
!ENDIF
!ENDIF
!ENDIF
!ENDIF
!ENDIF
!ENDIF

# -----------------------------------------------------------------------
# Standard inference rules
# -----------------------------------------------------------------------
.c{object\}.obj:
    $(cp) $(@B).c
.cpp{object\}.obj:
    $(cp) $(@B).cpp

# -----------------------------------------------------------------------
# The Target File List
# -----------------------------------------------------------------------
idxtst.exe: object\idxtst.obj ..\idxlib\$(C_Defs)$(M_Name).lib
      $(lp) object\idxtst.obj,,NUL,$(L_Libs) ..\idxlib\$(C_Defs)$(M_Name).lib,$(LnkDef);
      $(rc) idxtst.rc idxtst.exe
      copy  idxtst.exe $(C_Defs)$(M_Name).exe
      del   idxtst.res

# -----------------------------------------------------------------------
# The C and assembly File List
# -----------------------------------------------------------------------
object\idxtst.obj: idxtst.c ..\idxlib\genidx.h
