/************************************************************************/
/* Licensing Support Defs: LicSup.h                     V2.00  04/15/96 */
/* Copyright (c) 1987-1996 Andrew J. Michalik                           */
/*                                                                      */
/************************************************************************/
WORD  FAR PASCAL LicFilLod (LPSTR, VISMEMHDL FAR *);
WORD  FAR PASCAL LicFilRel (VISMEMHDL FAR *);
LPSTR FAR PASCAL LicStrXlt (LPSTR, LPSTR, WORD);
DWORD FAR PASCAL ChkRegIns (WORD, DWORD, LPCSTR);
DWORD FAR PASCAL ChkRegSer (WORD, LPCSTR);


