//-----------------------------------------------------------------------------
//                         InstallSHIELD Sample Files
// Copyright (c) 1990-1993, Stirling Technologies, Inc. All Rights Reserved
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
//      FILE:   DIALOGS.H
//
//      PURPOSE:
//         This header file defines the constants used in DIALOGS.DLG
//
//      RESOURCE: DIALOGS.DLG
//
//      RELATED FILES: DIALOGS.H
//
//
//-----------------------------------------------------------------------------

//---------------------------------------------------------------------------
//  Dialog Box Name IDs
//---------------------------------------------------------------------------

#define IDD_CONTINUE 1
#define IDD_BACK     9
#define IDD_HELP     11
#define IDD_NONE     12
#define IDD_PATH     16
#define IDD_S        419
#define IDD_T        420
#define IDD_EXIT     2


//---------------------------------------------------------------------------
//  Edit Control IDs
//---------------------------------------------------------------------------

#define IDD_EDIT     427
#define IDD_EDIT2    428



//---------------------------------------------------------------------------
//  ListBox Control IDs
//---------------------------------------------------------------------------

#define IDD_LIST1    429
#define IDD_LIST2    430

//---------------------------------------------------------------------------
//  Text Control IDs
//---------------------------------------------------------------------------

#define IDD_TEXT1    431
#define IDD_TEXT2    432
#define IDD_TEXT3    433
#define IDD_TEXT4    434
#define IDD_TEXT5    435
#define IDD_TEXT6    436
#define IDD_TEXT7    437
#define IDD_TEXT8    438
#define IDD_TEXT9    439
#define IDD_TEXT10   440

//---------------------------------------------------------------------------
//     Radio and Checkbox Button Control IDs
//---------------------------------------------------------------------------

#define IDD_B0       450
#define IDD_B1       451
#define IDD_B2       452
#define IDD_B3       453

//---------------------------------------------------------------------------
//  ICON IDs
//---------------------------------------------------------------------------

#define IDD_SETUP    202


//---------------------------------------------------------------------------
//  Special Pushbutton IDs
//---------------------------------------------------------------------------

#define IDD_SP1    521
#define IDD_SP2    522
#define IDD_SP3    523

//---------------------------------------------------------------------------
//  Status Text Field IDs
//---------------------------------------------------------------------------

#define IDD_STATUS1    661
#define IDD_STATUS2    662
#define IDD_STATUS3    663

//-----------------------------------------------------------------------------
// Dialog constants used in GivingOptionsWhenDoneInstalling when done with Installation
//-----------------------------------------------------------------------------

#define ID_DLG098                   1000
#define ID_DLG098_RUN               1001
#define ID_DLG098_EXIT              1002
#define ID_DLG098_HELP              1005

//---------------------------------------------------------------------------
//  Dialog Box Name IDs
//---------------------------------------------------------------------------

// Welcome To Setup of your application
#define DLG_WELCOME                     10

// Are you sure you want to quit ?
#define DLG_ASKQUIT                     20

// Where do you want to install the application ?
#define DLG_DESTPATH                    30

#define DLG_EXITFAILURE                 40
#define DLG_EXITQUIT                    60
#define DLG_EXITSUCCESS                 70
#define DLG_OPTIONS                     80
#define DLG_APPHELP                     90
#define DLG_SINGLELIST                 110
#define DLG_CHECK                      120
#define DLG_EXTENDEDLIST               130
#define DLG_MODELESS                   140
#define DLG_MULTILIST                  150
#define DLG_CUSTINST                   160
#define DLG_TOOBIG                     170
#define DLG_BADPATH                    180
#define DLG_ALREADYUSED                190
#define DLG_CDBADFILE                  200
#define DLG_CONFIRMREGINFO             210
#define DLG_GETNAME                    220
#define DLG_GETNAMECO                  230
#define DLG_GETCOMPANY                 240
#define DLG_HELP                       250
