#
# Standard compiler command line switches
#	d       Redefined macros
#	c       No link
#	AM      Medium memory model
#	Gsw     Stack probes & Windows
#	G2      80286 Instruction Set
#	G3      80386 Instruction Set
#	Gh      C5.1 compatible object
#	Ox      Max optimization (Note: C6.00a float op error for "ei")
#	Od      No optimization
#	W2      Intermediate warning level
#	Zd      Symbolic Debug
#	Zi      CodeView Debug
#	NT      Named text (code area) follows
#	Alnw	Check for DS==SS
#	V       Imbed version string
#
# Standard linker command line switches
#   NOD     No default library
#   A:x     Segment alignment (default = 512 bytes)
#   ST:x    Stack size larger than default 0x800 (2048)

# -----------------------------------------------------------------------
# Compile and Link options (distribution & debug)
# -----------------------------------------------------------------------
!IFDEF deb
# ---- DEBUG ----
ap=masm/MX/V/ZI
cp=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) $(M_Type) -W3 -G2  -Zp -Od -Zi
lp=link/NOD/NOE/NOI/M/CO$(L_Defs)
!ELSE
# ---- Default: DISTRIBUTION ----
ap=masm/MX/V
cp=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) $(M_Type) -W3 -G2s -Zp -Ocglt  
lp=link/NOD/NOE/NOI/M$(L_Defs)
!ENDIF

# -----------------------------------------------------------------------
# Version Control and Copyright Defs
# -----------------------------------------------------------------------
V_Note = "Copyright AJM, 800-234-VISI"

# -----------------------------------------------------------------------
# Library specific build arguments
# -----------------------------------------------------------------------
# ---- DEFAULT MS Large Emulator ----
W_Defs = -DDOS
M_Type = -AL -FPi
M_Name = mle
L_Libs = llibce
LnkDef = 
L_Defs = /ST:4096
rc = REM -No Rc-

# -----------------------------------------------------------------------
# Hardware specific build paths
# -----------------------------------------------------------------------
# ---- DEFAULT DIALOGIC ----
C_Defs = DLG
P_Defs = -D_P_MSW

# -----------------------------------------------------------------------
# Standard inference rules
# -----------------------------------------------------------------------
.c{object\}.obj:
    $(cp) $(@B).c

# -----------------------------------------------------------------------
# The Target File List
# -----------------------------------------------------------------------
$(C_Defs)eff.exe: object\geneff.obj                                     \
            object\effcfg.obj object\effini.obj object\cfgsup.obj       \
            object\fillod.obj object\fileff.obj                         \
            object\effvol.obj object\effchn.obj                         \
            object\efffqs.obj object\fqsmst.obj object\fqsobs.obj       \
            object\firdes.obj                                           \
            object\fftovr.obj object\fftlow.obj                         \
            object\effebs.obj object\ebssup.obj                         \
            object\filfnd.obj object\filrep.obj                         \
            object\wavfil.obj object\visfil.obj                         \
            object\filsup.obj object\fillow.obj                         \
            object\dosmem.obj object\dosmsg.obj object\usrstb.obj       \
            object\pcmfio.obj object\pcmini.obj object\pcmqry.obj       \
            object\blkcvt.obj object\mpcsup.obj
    $(lp)   @$(C_Defs)$(M_Name).rsp $(L_Libs),$(LnkDef);
    copy geneff.exe ..\reldev\dos\frqeff.exe   

# -----------------------------------------------------------------------
# The C and assembly File List
# -----------------------------------------------------------------------
object\geneff.obj: geneff.c geneff.h  ..\fiodev\filutl.h                \
    ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\regdev\tbxreg.h
object\effcfg.obj: effcfg.c geneff.h ..\fiodev\filutl.h                 \
    ..\os_dev\dosmem.h ..\os_dev\dosmsg.h ..\pcmdev\genpcm.h ..\pcmdev\pcmsup.h ..\fiodev\genfio.h ..\os_dev\cfgsup.h
object\effini.obj: effini.c geneff.h ..\fiodev\filutl.h                 \
    ..\os_dev\dosmem.h ..\os_dev\dosmsg.h ..\pcmdev\genpcm.h ..\pcmdev\pcmsup.h ..\regdev\tbxreg.h ..\os_dev\cfgsup.h 
object\fillod.obj: fillod.c geneff.h ..\os_dev\dosmem.h                 \
    ..\os_dev\dosmsg.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\fiodev\wavfil.h ..\regdev\tbxreg.h
object\fileff.obj: fileff.c geneff.h ..\fiodev\filutl.h                 \
    ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h
object\effvol.obj: ..\effdev\effvol.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\effvol.c   
object\effchn.obj: ..\effdev\effchn.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\effchn.c   
object\efffqs.obj: ..\effdev\efffqs.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\efffqs.c   
object\fqsmst.obj: ..\effdev\fqsmst.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\fqsmst.c   
object\fqsobs.obj: ..\effdev\fqsobs.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\fqsobs.c   
object\firdes.obj: ..\effdev\firdes.c ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\firdes.c   
object\fftovr.obj: ..\effdev\fftovr.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\fftovr.c   
object\fftlow.obj: ..\effdev\fftlow.c ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\fftlow.c
object\effebs.obj: ..\effdev\effebs.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\effebs.c   
object\ebssup.obj: ..\effdev\ebssup.c ..\os_dev\dosmem.h ..\pcmdev\genpcm.h ..\effdev\geneff.h ..\effdev\effsup.h
    $(cp)   ..\effdev\ebssup.c   
object\filfnd.obj: ..\fiodev\filfnd.c ..\fiodev\filutl.h ..\os_dev\dosmsg.h
    $(cp)   ..\fiodev\filfnd.c
object\filrep.obj: ..\fiodev\filrep.c ..\fiodev\filutl.h
    $(cp)   ..\fiodev\filrep.c
object\filsup.obj: ..\fiodev\filsup.c ..\fiodev\filutl.h
    $(cp)   ..\fiodev\filsup.c
object\wavfil.obj: ..\fiodev\wavfil.c ..\fiodev\filutl.h ..\fiodev\wavfil.h
    $(cp)   ..\fiodev\wavfil.c
object\visfil.obj: ..\fiodev\visfil.c ..\fiodev\filutl.h ..\fiodev\visfil.h
    $(cp)   ..\fiodev\visfil.c
object\fillow.obj: ..\fiodev\fillow.c ..\fiodev\filutl.h
    $(cp)   ..\fiodev\fillow.c
object\cfgsup.obj: ..\os_dev\cfgsup.c ..\os_dev\cfgsup.h
    $(cp)   ..\os_dev\cfgsup.c
object\dosmem.obj: ..\os_dev\dosmem.c ..\usrdev\usrstb.h ..\os_dev\dosmem.h
    $(cp)   ..\os_dev\dosmem.c
object\dosmsg.obj: ..\os_dev\dosmsg.c ..\usrdev\usrstb.h ..\os_dev\dosmsg.h
    $(cp)   ..\os_dev\dosmsg.c
object\usrstb.obj: ..\usrdev\usrstb.c ..\usrdev\usrstb.h
    $(cp)   ..\usrdev\usrstb.c
object\winmem.obj: ..\os_dev\winmem.c ..\os_dev\winmem.h
    $(cp)   ..\os_dev\winmem.c
object\winmsg.obj: ..\os_dev\winmsg.c ..\os_dev\winmsg.h
    $(cp)   ..\os_dev\winmsg.c
object\pcmfio.obj: ..\pcmdev\pcmfio.c ..\pcmdev\genpcm.h ..\pcmdev\pcmsup.h
    $(cp)   ..\pcmdev\pcmfio.c
object\pcmini.obj: ..\pcmdev\pcmini.c ..\pcmdev\genpcm.h ..\pcmdev\pcmsup.h
    $(cp) $(P_Defs) ..\pcmdev\pcmini.c
object\pcmqry.obj: ..\pcmdev\pcmqry.c ..\pcmdev\genpcm.h ..\pcmdev\pcmsup.h
    $(cp)   ..\pcmdev\pcmqry.c
object\blkcvt.obj: ..\pcmdev\blkcvt.c ..\pcmdev\genpcm.h ..\pcmdev\pcmsup.h
    $(cp)   ..\pcmdev\blkcvt.c
object\mpcsup.obj: ..\pcmdev\mpcsup.c ..\pcmdev\genpcm.h ..\pcmdev\pcmsup.h
    $(cp)   ..\pcmdev\mpcsup.c
